builddocs:
  only:
    - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

testjob:
  only:
    - master
  script:
    # save PySiTK folder path just in case
    - export pysitk_dir=$(pwd)

    # create a virtual env to dev-test
    - venv="pysitk-test-py2"
    - mypython=$(which python2)
    - virtualenv -p $mypython $venv
    - cd $venv
    - venv_dir=$(pwd)
    - source bin/activate
    
    # copy ITK_me path
    SITEDIR=$(python -m site --user-site)
    mkdir -p "$SITEDIR"
    cp Wrapping/Generators/Python/WrapITK.pth $SITEDIR

    # print Python version to CI output
    - which python
    - python --version
    - cd $pysitk_dir

    - pip install -r requirements.txt

    # tests
    - python -m unittest discover -s "test" -p "*_test.py"
    

  tags:
    - gift-adelie    